apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::167693783846:role/eksctl-cicd-demo-nodegroup-ng-1-NodeInstanceRole-5XS3YDBAXCW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::167693783846:role/CodeBuildKubectlRole
      username: CodeBuildKubectlRole
  mapUsers: |
    []
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::167693783846:role/eksctl-cicd-demo-nodegroup-ng-1-NodeInstanceRole-5XS3YDBAXCW\n  username: system:node:{{EC2PrivateDNSName}}\n","mapUsers":"[]\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-03-07T03:12:33Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"8769","uid":"ba893249-f2b9-4af8-ac16-5207c1c33d24"}}
  creationTimestamp: "2023-03-07T03:12:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "12597"
  uid: ba893249-f2b9-4af8-ac16-5207c1c33d24
